/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fmblzf_androidndk_ndk_AndroidNDK */

#ifndef _Included_com_fmblzf_androidndk_ndk_AndroidNDK
#define _Included_com_fmblzf_androidndk_ndk_AndroidNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fmblzf_androidndk_ndk_AndroidNDK
 * Method:    startService
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_fmblzf_androidndk_ndk_AndroidNDK_startService
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_fmblzf_androidndk_ndk_AndroidNDK
 * Method:    startActivity
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fmblzf_androidndk_ndk_AndroidNDK_startActivity
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fmblzf_androidndk_ndk_AndroidNDK
 * Method:    sendBroadCast
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fmblzf_androidndk_ndk_AndroidNDK_sendBroadCast
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fmblzf_androidndk_ndk_AndroidNDK
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fmblzf_androidndk_ndk_AndroidNDK_test
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
